import datetime
import urllib.parse
from google.oauth2.credentials import Credentials
from googleapiclient.discovery import build
from django.conf import settings
from allauth.socialaccount.models import SocialToken, SocialApp

def get_google_credentials(user):
    try:
        # Fetch the token for the user from allauth
        token = SocialToken.objects.get(account__user=user, account__provider='google')
        app = SocialApp.objects.get(provider='google')
        
        return Credentials(
            token=token.token,
            refresh_token=token.token_secret,
            token_uri='https://oauth2.googleapis.com/token',
            client_id=app.client_id,
            client_secret=app.secret
        )
    except Exception as e:
        print(f"Could not get tokens for user {user}: {e}")
        raise e

def create_calendar_event(user, title, date, time, role="General"):
    start_datetime_str = f"{date}T{time}:00"
    
    # Calculate exactly 30 minutes from start 
    dt_obj = datetime.datetime.strptime(f"{date} {time}", "%Y-%m-%d %H:%M")
    end_dt_obj = dt_obj + datetime.timedelta(minutes=30)
    end_datetime_str = end_dt_obj.strftime("%Y-%m-%dT%H:%M:00")

    try:
        creds = get_google_credentials(user)
        service = build('calendar', 'v3', credentials=creds)

        event_body = {
            'summary': title,
            'description': f'PrepMind AI Mock Interview\nRole: {role}\nGenerated by PrepMind AI',
            'start': {
                'dateTime': start_datetime_str,
                'timeZone': 'UTC', 
            },
            'end': {
                'dateTime': end_datetime_str,
                'timeZone': 'UTC',
            },
            'conferenceData': {
                'createRequest': {
                    'requestId': f"prepmind-event-{user.id}-{datetime.datetime.now().timestamp()}",
                    'conferenceSolutionKey': {'type': 'hangoutsMeet'}
                }
            }
        }

        event = service.events().insert(
            calendarId='primary', 
            body=event_body, 
            conferenceDataVersion=1
        ).execute()
        return event.get('htmlLink'), event.get('hangoutLink')
        
    except Exception as e:
        print(f"[CALENDAR ERR] OAuth Token setup failed: {e}")
        
        # Format string for Google URL `YYYYMMDDTHHMMSS`
        d_start = dt_obj.strftime("%Y%m%dT%H%M%S")
        d_end = end_dt_obj.strftime("%Y%m%dT%H%M%S")
        
        encoded_title = urllib.parse.quote(title)
        encoded_details = urllib.parse.quote(f"PrepMind Mock Interview\nRole: {role}")
        
        fallback_link = f"https://calendar.google.com/calendar/render?action=TEMPLATE&text={encoded_title}&dates={d_start}/{d_end}&details={encoded_details}"
        
        return fallback_link, "https://meet.google.com/new"
