# Generated by Django 4.2.16 on 2026-03-27 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='credits_count',
            field=models.IntegerField(default=1),
        ),
    ]
