# Generated by Django 4.2.16 on 2026-03-27 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='interview_credits',
            field=models.IntegerField(default=3),
        ),
    ]
