# Generated by Django 4.2.16 on 2026-03-28 04:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_customuser_company_name_customuser_is_hr_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='HRInterviewRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.TextField(blank=True, null=True)),
                ('scheduled_date', models.DateField(blank=True, null=True)),
                ('scheduled_time', models.TimeField(blank=True, null=True)),
                ('is_read_by_candidate', models.BooleanField(default=False)),
                ('is_read_by_hr', models.BooleanField(default=True)),
                ('status', models.CharField(default='Pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_interview_requests', to=settings.AUTH_USER_MODEL)),
                ('hr_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_interview_requests', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='HRUnlockedCandidate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unlocked_at', models.DateTimeField(auto_now_add=True)),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='unlocked_by_hrs', to=settings.AUTH_USER_MODEL)),
                ('hr_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='unlocked_candidates_by_hr', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('hr_user', 'candidate')},
            },
        ),
    ]
