# Generated by Django 4.2.16 on 2026-03-28 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_hrinterviewrequest_hrunlockedcandidate'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='hr_credits',
            field=models.IntegerField(default=0),
        ),
    ]
