# Generated by Django 4.2.29 on 2026-03-14 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interviews', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='interviewsession',
            name='communication_score',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='interviewsession',
            name='confidence_score',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='interviewsession',
            name='feedback_text',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='interviewsession',
            name='question_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='interviewsession',
            name='stage',
            field=models.CharField(default='tech1', max_length=50),
        ),
        migrations.AddField(
            model_name='interviewsession',
            name='technical_score',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='question',
            name='is_coding',
            field=models.BooleanField(default=False),
        ),
    ]
