# Generated by Django 4.2.16 on 2026-03-27 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interviews', '0002_interviewsession_communication_score_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interviewsession',
            name='status',
            field=models.CharField(choices=[('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed'), ('CANCELLED_BY_USER', 'Cancelled by User'), ('FAILED_BY_AI', 'Failed by AI'), ('EXPIRED', 'Expired')], default='IN_PROGRESS', max_length=50),
        ),
    ]
