# Generated by Django 4.2.16 on 2026-03-27 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interviews', '0003_alter_interviewsession_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='interviewsession',
            name='scheduled_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='interviewsession',
            name='status',
            field=models.CharField(choices=[('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed'), ('CANCELLED_BY_USER', 'Cancelled by User'), ('FAILED_BY_AI', 'Failed by AI'), ('EXPIRED', 'Expired'), ('SCHEDULED', 'Scheduled')], default='IN_PROGRESS', max_length=50),
        ),
    ]
